### PR TITLE
Combining all work on servlets and dl layer

### PR DESCRIPTION
**Pull request by JatinKumarKushwaha**
Combining work by @illusionnn on servlets with work on dl layer for integration testing and QA. Will test here and then merge with main.

### CODE REVIEW

**Comment by illusionnn** [comment]
all good

**Comment by JatinKumarKushwaha** [comment]
merged

**Review by illusionnn — COMMENTED** [review]
all good

**Review by JatinKumarKushwaha — COMMENTED** [review]
Done.

**Pull request closed without merging**
